# ekf config file
ekf_filter_node:
  ros_parameters:
    frequency: 30.0
#if true, ignores small variations in ground plane and assume a 2d planar world
    two_d_mode: false
    publish_acceleration: true
# if true, publishes transformation over /tf topic
    publish_tf: true

# set the map, odom, base_link, and world frames 
# set world frame to odom because using position data with wheel encoders and IMU
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odometry
    odom0_config: [true, true, false,
                  false, false, true,
                  true,  true,  false,
                  false, false, true,
                  false, false, false]

    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true, true, true]
